### ISSUE TITLE
Carved Out Water

### ISSUE THREAD

**Issue by WenXin20** [PersonTheCat/CaveGenerator#11]
Forge v14.23.4.2750-1.12.2
Cave Generator v0.8

Caves seem to carve holes into water, such as this ocean.
![2018-08-15_22 45 48](https://user-images.githubusercontent.com/12000593/44189719-9e645600-a0e9-11e8-9f85-82b0b2806d22.png)

**Comment by PersonTheCat** [comment]
Thanks. This is a bug that happens with certain kinds of caves. I just haven't written a better way to test for water before spawning yet them because each kind of cave needs its own method. I'm actually hoping to write something a little bit neater that can handle multiple different shapes without impacting performance. I'll try to work on that before the next release.

**Comment by WenXin20** [comment]
Thanks, it also looks like caves break the surface a lot, which can make the terrain look a bit messy. Is there a way to change that in the config?

**Comment by PersonTheCat** [comment]
There is not, actually, but I'll take a look at it. I think that one's just related to testing, but I did mean to remove it by now, so I'll do that soon. Sorry about that! This mod is still in beta, to be sure.

**Comment by PersonTheCat** [comment]
Actually, I also took another look at caves generating in water, but have not been able to produce anything this severe. The only problem I'm getting is that cavern-type caves will leave holes on the ocean floor, but they don't generate through oceans. Normal caves and rooms also do not, although ravines sometimes do (they generate in pillars near water, which is related to the original bug I was mentioning). I also tried both 1.12.1 and 1.12.2, Forge v. 2705. Is there any way you could share your preset and seed with me?

**Comment by WenXin20** [comment]
I used forge 2750 for 1.12.2. The only thing different is that I enabled the example presets and added stalagmites to some of the presets.
And here is the presets (I had to rename these to a .log file to upload to here, .json doesn't work):
[caverns.log](https://github.com/PersonTheCat/CaveGenerator/files/2294799/caverns.log)
[flooded_vanilla.log](https://github.com/PersonTheCat/CaveGenerator/files/2294803/flooded_vanilla.log)
[large_caves.log](https://github.com/PersonTheCat/CaveGenerator/files/2294804/large_caves.log)
[ravines.log](https://github.com/PersonTheCat/CaveGenerator/files/2294806/ravines.log)
[spirals.log](https://github.com/PersonTheCat/CaveGenerator/files/2294810/spirals.log)
[stalactites.log](https://github.com/PersonTheCat/CaveGenerator/files/2294811/stalactites.log)
[tunnels.log](https://github.com/PersonTheCat/CaveGenerator/files/2294813/tunnels.log)
[vanilla.log](https://github.com/PersonTheCat/CaveGenerator/files/2294815/vanilla.log)

**Comment by WenXin20** [comment]
I can get you the seed once my game loads, although terrain will be different since I have several biome-adding mods.

**Comment by PersonTheCat** [comment]
Okay, good. I just want to make sure you know that each preset gets its own standalone generator. I know other users have been a little confused by that, so I am gonna try to somehow make that more obvious. I'm just going to retest these individually again to see if a particular one of them is causing issues. I have some errands to run and then a couple of other things to look at and then I'll let you know. Thanks for your help!

**Comment by PersonTheCat** [comment]
So, I still never quite experienced the kinds of holes that were in the picture, but I did work on water detection for both the ravines and the large caverns. That'll be in the next update. Let me know if you try it and whether you think it's any better. Thanks again!

**Comment by WenXin20** [comment]
Thanks!

**Comment by PersonTheCat** [comment]
Closing this issue, because I haven't seen it in a while. Especially since the rewrite, I believe it was fixed inadvertently.

**Comment by dadobug1111** [comment]
It seems this bug is not quite fixed.
My oceans are littered with massive air bubbles at the bottom
![2019-08-20_12 53 23](https://user-images.githubusercontent.com/33583954/63372079-0677f880-c34b-11e9-9733-b6a5289e9264.png)
This is caused by a combination of the underground forest and vanilla presets whenever there is a deep ocean.

**Comment by PersonTheCat** [comment]
I couldn't reproduce it. Here's a screenshot I took using the latest version in which the caverns used in underground_forest dodge the ocean floor. 
![2019-08-20_18 21 28](https://user-images.githubusercontent.com/33143148/63391490-3c7fa180-c378-11e9-9748-afd906e06909.png)
@dadobug1111 Is there any other info you can provide me about your setup? I can't otherwise imagine how this could happen anymore.

**Comment by dadobug1111** [comment]
It seems to have something to do with the names of the files. If the vanilla file has spaces, underscores, or any number 1-9 (0 works fine), the caverns will breach. Also, if the vanilla file is after the cavern file, breaches happen.

**Comment by PersonTheCat** [comment]
I did try this and still could not reproduce the issue. Which version of the mod are you using? Also, which Forge version?

**Comment by dadobug1111** [comment]
forge 14.23.5.2838
cave generator 0.15

**Comment by PersonTheCat** [comment]
I've been frantically searching for what could cause this issue and I think I finally found something that looked culpable in the code. Please try this version and let me know if it fixes things for you. 

[CaveGenerator-0.16.zip](https://github.com/PersonTheCat/CaveGenerator/files/3532228/CaveGenerator-0.16.zip)

**Comment by dadobug1111** [comment]
It appears to be working. Thanks for the fix!
